### ISSUE TITLE
Style 2 doesn't work with hyphenated classes

### ISSUE THREAD

**Issue by chetstone** [fab1an/react-native-tachyons#6]
Javascript doesn't like hyphens in property names. So when I do
```
<View style={[s.flx-i,s.bg-gold]}>
```
I get `Can't find variable i`

Is there a workaround for this other than to use `NativeTachyons.wrap`?

**Comment by fab1an** [comment]
I always use the wrapper, so I haven't noticed that. A simple, but ugly, workaround would be to use `s["flx-i"]`.

The hyphens are used instead of underscores to match the original tachyons' names, and they're more readable.

Maybe I should add underscore variants, but I'm not sure if that's not too confusing.

**Comment by fab1an** [comment]
Is there a reasons against using the wrapper?

**Comment by fab1an** [comment]
Just released `1.7` which gives you names with underscores.

**Comment by chetstone** [comment]
Ah, thank you. Typically css names are referred to in code with camelCase and that would be preferable but underscores are OK: I don't know how you'd say `b--green` in camelCase. (What's the extra hyphen for anyway?)

It's personal preference but I find it a nuisance having to wrap each of my components to use this. And I think `style={[s.flx_i,s.bg_gold]}` is more idiomatic and self-documenting in react-native code. 

Anyway, most of my components are generated with React.createClass and I don't know if those can be wrapped. The README only documents wrapping ES6 classes. 

Again, thank you. I do like the idea of using essentially inline styles with compact syntax and I like your spacing and fontsize systems. (At least in theory --- can't wait to try them!)

**Comment by fab1an** [comment]
>  I don't know how you'd say b--green in camelCase. (What's the extra hyphen for anyway?)

That comes from the original tachyons css, I think because they used hyphens to separate media queries. I kinda like it because -- reminds me of a borderline visually.

> It's personal preference but I find it a nuisance having to wrap each of my components to use this.

Agreed. I have to wrap all my components anyway, because I have other shared behaviour as well.

I'm thinking about converting the wrapper to a babel-plugin sometime. Then you wouldn't have to change your code (but there would still be a string property).

> I do like the idea of using essentially inline styles with compact syntax and I like your spacing and fontsize systems.

👍  have fun. ;)

**Comment by fab1an** [comment]
@chetstone Would you use the wrapper if it were a babel plugin = the "cls" string automatically translated to properties?

**Comment by chetstone** [comment]
Probably not

**Comment by fab1an** [comment]
btw, the reasons for the double-hypens: https://github.com/tachyons-css/tachyons/issues/216#issuecomment-233793808
